# Generated by Django 2.2.4 on 2019-10-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0004_auto_20191001_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gift',
        ),
    ]
