# Generated by Django 2.2.4 on 2019-10-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0008_auto_20191003_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ImageField(default='', null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('babygift', 'BABYGIFT'), ('birthdaygift', 'BIRTHDAYGIFT'), ('accentsgift', 'ACCENTSGIFT'), ('cristamgift', 'CRISTAMGIFT'), ('toysgift', 'TOYSGIFT'), ('valentinegift', 'VALENTINEGIFT'), ('artificialgift', 'ARTIFICIALGIFT'), ('giftforher', 'GIFTFORHER'), ('giftforhim', 'GIFTFORHIM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
