# Generated by Django 2.2.4 on 2019-10-03 06:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0012_auto_20191003_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 6, 42, 17, 209417, tzinfo=utc)),
        ),
    ]
