# Generated by Django 2.2.4 on 2019-10-03 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0014_auto_20191003_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('babygift', 'BABYGIFT'), ('birthdaygift', 'BIRTHDAYGIFT'), ('accentsgift', 'ACCENTSGIFT'), ('cristamgift', 'CRISTAMGIFT'), ('toysgift', 'TOYSGIFT'), ('valentinegift', 'VALENTINEGIFT'), ('artificialgift', 'ARTIFICIALGIFT'), ('giftforher', 'GIFTFORHER'), ('giftforhim', 'GIFTFORHIM')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 6, 43, 8, 457222, tzinfo=utc)),
        ),
    ]
