# Generated by Django 2.2.4 on 2019-10-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0020_cart_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='username',
        ),
        migrations.AddField(
            model_name='cart',
            name='usern',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
