# Generated by Django 2.2.4 on 2019-10-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0021_auto_20191008_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='usern',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
