# Generated by Django 2.2.4 on 2019-10-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0023_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='addess2',
            new_name='address2',
        ),
    ]
