# Generated by Django 2.2.4 on 2019-10-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycart', '0024_auto_20191009_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='statr',
            new_name='state',
        ),
    ]
